logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
server:
  contextPath: /
  port: 19003
spring:
  application:
    name: docker.service.network.c


service_d_url: http://localhost:19004
service_e_url: http://localhost:19005
