logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
server:
  contextPath: /
  port: 8080
spring:
  application:
    name: docker.service.network.c

service_d_url: ${service_d_url}
service_e_url: ${service_e_url}

