server.port: 18080

#logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    
info.tcb: DEBUG
debug: true

spring:
  aop:
    proxy-target-class: true

#spring.redis.host: localhost
#spring.redis.host: 192.168.99.100
#spring.redis.port: 6379


#zuul.debug.request: true
#zuul.debugRouting: true

security:
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: http://localhost:19999/uaa/oauth/token
      userAuthorizationUri: http://localhost:19999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----

zuul:
  routes:
    resource:
      sensitiveHeaders:
      sensitive-headers: 
      path: /rest/**
      url: http://localhost:19000/rest
    user:
      path: /user/**
      url: http://localhost:19999/uaa/user
           