# when commented spring bind to all interfaces
#server.address: 127.0.0.1
server.port: 8080

#security.user.password=password

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG

zuul:
  routes:
    a:
      path: /a/**
      url: http://service-network-a:8080/
    b:
      path: /b/**
      url: http://service-network-b:8080/
    c:
      path: /c/**
      url: http://service-network-c:8080/
    d:
      path: /d/**
      url: http://service-network-d:8080/
    e:
      path: /e/**
      url: http://service-network-e:8080/
