logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
server:
  contextPath: /
  port: 19001
service_b_url: http://localhost:19002
service_c_url: http://localhost:19003
spring:
  application:
    name: docker.service.network.a
