spring.application.name=docker.service.network.a
# when commented spring bind to all interfaces
#server.address: 127.0.0.1
server.port: 19001
server.contextPath: /

#security.user.password=password

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.level.org.springframework.security: DEBUG

service_b_url: http://localhost:19002
service_c_url: http://localhost:19003

#eureka.client.serviceUrl.defaultZone=http://127.0.0.1:18761/eureka/
#eureka.instance.hostname=localhost
#eureka.instance.ipAddress=127.0.0.1
#eureka.instance.ip-address=127.0.0.1
#eureka.instance.prefer-ip-address=true
