spring.application.name=docker.service.network.e
# when commented spring bind to all interfaces
#server.address: 127.0.0.1
server.port: 19005
server.contextPath: /

#security.user.password=password

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.level.org.springframework.security: DEBUG

#eureka.client.serviceUrl.defaultZone=http://127.0.0.1:18761/eureka/
#eureka.instance.hostname=localhost
#eureka.instance.prefer-ip-address=true
