apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-network-b 
spec:
  replicas: 1
  selector:
    matchLabels:
      run: service-network-b
  template:
    metadata:
      labels:
        run: service-network-b
    spec:
      containers:
      - name: service-network-b
        image: docker_service_network/b:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-network-b
  labels:
    run: service-network-b
    tier: backend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: service-network-b
  sessionAffinity: None
