services:

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    hostname: docker-rabbitmq
    volumes:
      - "rabbitmq:/var/lib/rabbitmq/mnesia"
    environment:
      - 'RABBITMQ_DEFAULT_PASS=guest2'
      - 'RABBITMQ_DEFAULT_USER=guest2'
      - 'RABBITMQ_PASSWORD=user'
      - 'RABBITMQ_USERNAME=user'
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  rabbitmq: